4.2

diff --git a/tests/execscript b/tests/execscript
--- a/tests/execscript
+++ b/tests/execscript
@@ -48,6 +48,8 @@ echo $?
 
 # try sourcing a binary file -- post-2.04 versions don't do the binary file
 # check, and will probably fail with `command not found', or status 127
+# bash-4.1 and later check for 256 NUL characters and fail as binary files
+# if there are more than that, it's probably binary
 . ${THIS_SH} 2>/dev/null
 echo $?
 
@@ -107,6 +109,18 @@ ${THIS_SH} ./exec7.sub
 
 ${THIS_SH} -i ./exec8.sub
 
+${THIS_SH} ./exec9.sub
+
 true | `echo true` &
 
 echo after
+
+# Problem with bash at least back to version 3.0
+${THIS_SH} -c 'VAR=0; VAR=1 command exec; exit ${VAR}'
+
+# problem with bash through bash-4.1
+(
+        exec /var/empty/nosuch
+        echo bad
+) 2>/dev/null
+[ $? = 127 ] || echo FAIL: bad exit status $? at $LINENO
